baseURL = "http://perfbytes.com/"
languageCode = "en-us"
title = "PerfBytes Web Site"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
